### ISSUE TITLE
redirect in getServerSideProps causes server to crash

### ISSUE THREAD

**Issue by paragbaxi** [dabit3/next.js-authentication-aws#1]
Related to https://github.com/vercel/next.js/discussions/14890

How did you get yours to work?

`res.writeHead(302, { Location: '/profile' });`

**Comment by paragbaxi** [comment]
```
error, user not authenticated
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:547:11)
    at DevServer.sendHTML (/Users/paragbaxi/Documents/GitHub/nextjs-authentication-aws/next.js-authentication-aws/node_modules/next/dist/server/next-dev-server.js:35:5)
    at DevServer.render (/Users/paragbaxi/Documents/GitHub/nextjs-authentication-aws/next.js-authentication-aws/node_modules/next/dist/next-server/server/next-server.js:56:37)
    at async Object.fn (/Users/paragbaxi/Documents/GitHub/nextjs-authentication-aws/next.js-authentication-aws/node_modules/next/dist/next-server/server/next-server.js:31:107)
    at async Router.execute (/Users/paragbaxi/Documents/GitHub/nextjs-authentication-aws/next.js-authentication-aws/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/Users/paragbaxi/Documents/GitHub/nextjs-authentication-aws/next.js-authentication-aws/node_modules/next/dist/next-server/server/next-server.js:49:494)
    at async DevServer.handleRequest (/Users/paragbaxi/Documents/GitHub/nextjs-authentication-aws/next.js-authentication-aws/node_modules/next/dist/next-server/server/next-server.js:17:101) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:657:15)
    at ServerResponse.end (_http_outgoing.js:777:7)
    at ServerResponse.end (/Users/paragbaxi/Documents/GitHub/nextjs-authentication-aws/next.js-authentication-aws/node_modules/next/dist/compiled/compression/index.js:1:148805)
    at DevServer.handleRequest (/Users/paragbaxi/Documents/GitHub/nextjs-authentication-aws/next.js-authentication-aws/node_modules/next/dist/next-server/server/next-server.js:17:189)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:716:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
error Command failed with exit code 1.
```

**Comment by weisisheng** [comment]
Hmm, +1.  Believe it is related to the last line "    return {props: {} } " but can't find an answer yet.

**Comment by talves** [comment]
@weisisheng getting the same error. Did you happen to find a solution to this issue?

tracking: https://github.com/vercel/next.js/issues/16764

**Comment by talves** [comment]
Here is the workaround until this is solved for `res.writeHead`

`pages/protected.js`
```javascript
import { withSSRContext } from "aws-amplify";

function Protected({ username }) {
  if (!username) return null;
  return <h1>Hello {username} from SSR route!</h1>;
}

/*
A more secure way is using SSR and server side redirects.
*/
export async function getServerSideProps({ req, res }) {
  const { Auth } = withSSRContext({ req });
  try {
    const user = await Auth.currentAuthenticatedUser();
    return {
      props: {
        authenticated: true,
        username: user.username,
      },
    };
  } catch (err) {
    /* This creates an error */
    // res.writeHead(302, { Location: "/profile" });
    // res.end();
    /* This is workaround for above until fixed */
    res.setHeader("Location", "/profile");
    res.statusCode = 302;
  }
  return { props: {} };
}

export default Protected;
```

@dabit3 just let me know if you want a PR for this workaround
